
#...............................................................................................
# build, push and cache the docker image. I have to add the 'BUILD_DATE' arg in the Dockerfile
# See also: https://github.com/mlampros/IceSat2R/blob/master/.github/workflows/docker_image.yml
#...............................................................................................

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: docker_img

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TIC_DEPLOY_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ github.repository_owner }}/openimager:rstudiodev
          cache-from: type=registry,ref=${{ github.repository_owner }}/openimager:buildcache
          cache-to: type=registry,ref=${{ github.repository_owner }}/openimager:buildcache,mode=max
